"""API contracts for the customer-service assistant."""

from datetime import date, datetime, time
from enum import StrEnum
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field


class AssistantMessageRequest(BaseModel):
    """Customer message and scheduling context required by the assistant."""

    barber_id: UUID
    appointment_date: date
    customer_id: UUID | None = None
    conversation_id: UUID | None = None
    message: str = Field(min_length=1, max_length=2000)


class AssistantMessageResponse(BaseModel):
    """Text generated by the scheduling assistant."""

    reply: str
    model: str
    action: Literal["availability", "customer_required", "confirmation_required", "booked"] = (
        "availability"
    )
    conversation_id: UUID | None = None
    appointment_id: UUID | None = None
    starts_at: datetime | None = None


class AssistantIntentName(StrEnum):
    """Actions the model may request from the deterministic workflow."""

    CHECK_AVAILABILITY = "check_availability"
    SELECT_SLOT = "select_slot"
    CONFIRM_BOOKING = "confirm_booking"


class AssistantIntent(BaseModel):
    """Structured interpretation of one customer message."""

    intent: AssistantIntentName
    selected_time: time | None = None
